import { Inter } from 'next/font/google';
import Header from '@/components/header/header';
import ReduxProvider from '@/components/provider';
import '@/styles/reset.scss';
import '@/styles/vars.scss';

export const metadata = {
    title: {
        template: '%s | Zen.com',
        default: 'Zen.com',
    },
    description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export default function RootLayout({ children }) {
    return (
        <ReduxProvider>
            <html lang='en' data-theme='dark'>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </html>
        </ReduxProvider>
    );
}