# Generated by Django 4.2.5 on 2023-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='article_previews'),
        ),
    ]
