# Generated by Django 4.2.5 on 2023-09-16 14:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_created_at_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.article_preview_path),
        ),
    ]
